# Generated by Django 4.1.13 on 2024-03-07 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_teacher_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='floor',
        ),
        migrations.AddField(
            model_name='floor',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='navigation.department'),
        ),
    ]
