# Generated by Django 4.1.13 on 2024-03-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_remove_department_floor_floor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='department',
        ),
        migrations.AddField(
            model_name='floor',
            name='department',
            field=models.ManyToManyField(blank=True, to='navigation.department'),
        ),
    ]
