# Generated by Django 4.1.13 on 2024-03-07 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0006_remove_floor_department_floor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='navigation.floor'),
        ),
    ]
