# Generated by Django 4.1.13 on 2024-03-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0008_teacher_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='floor_no',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
